django/core/urls.py
# imports Django
from django.urls import path

# imports from this project
from . import views

# set the namespace for this app
app_name = 'core'

urlpatterns = [
    # set the landing page for this app
    # ex: /core/
    path('', views.about, name='about'),

    # ex: /core/about/
    path('about/', views.about, name='about'),
]

django/crumbs/urls.py
# imports Django
from django.urls import path

# imports from this project
from . import views


# set the namespace for this app
app_name = 'crumbs'

urlpatterns = [
    # set the landing page for this app
    # ex: /crumbs/
    path('', views.about, name='about'),

    # ex: /crumbs/about/
    path('about/', views.about, name='about'),


    # ex: /crumbs/expense_create/
    path('expense_create/', views.expense_create, name='expense_create'),

    # ex: /crumbs/expense_sand/
    #path('expense_sand/', views.expense_sand, name='expense_sand'),
    path('expense_sand/<int:receipt_id>/', views.expense_sand, name='expense_sand'),
    path('expense_paper/', views.expense_paper, name='expense_paper'),

    # ex: /crumbs/expense_list/
    path('expense_list/', views.expense_list, name='expense_list'),


    # ex: /crumbs/receipt_list/
    path('receipt_list/', views.receipt_list, name='receipt_list'),

    # ex: /crumbs/4/
    path('receipt/<int:receipt_id>/', views.receipt_read, name='receipt_read'),

    # ex: /crumbs/receipt_upload/
    path('receipt_upload/', views.receipt_upload, name='receipt_upload'),
]

django/myproject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('core/', include('core.urls')),
    path('crumbs/', include('crumbs.urls')),
    path('people/', include('people.urls')),
]


# This is the landing page. Redirects the base URL '/' (or empty) to '/inventories/'.
# Taken from https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/skeleton_website
# Leave the first parameter of the path function empty to imply '/'.
# If you write the first parameter as '/' Django will give you the following warning:
# ?: (urls.W002) Your URL pattern '/' has a route beginning with a '/'.
# Remove this slash as it is unnecessary.
from django.views.generic.base import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='/core/', permanent=True)),
]

# to serve media in the development server
# https://simpleisbetterthancomplex.com/tutorial/2016/08/01/how-to-upload-files-with-django.html
from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django/crumbs/models.py
# imports, Django core
from django.db import models


class Expense(models.Model):
    """Represents the Expense object."""
    amount = models.DecimalField(
        max_digits=6,
        decimal_places=2,
        blank=True,
        null=True)
    #date = models.DateTimeField('date of expense')
    date = models.DateField('date of expense', blank=True, null=True)
    purpose = models.CharField(max_length=200, blank=True, null=True)
    incurred_by = models.ForeignKey(
        'people.User',
        on_delete=models.SET_NULL,
        blank=True,
        null=True)
    #created = models.DateTimeField(auto_now_add=True)
    #updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        """
        String to represent the User object (in Admin site etc.)
        """
        return self.purpose

    class Meta:
        ordering = ('amount',)


# https://simpleisbetterthancomplex.com/tutorial/2016/08/01/how-to-upload-files-with-django.html
class Receipt(models.Model):
    receipt = models.FileField(upload_to='receipts/')
    #receipt = models.ImageField(upload_to='receipts/')
    uploaded_at = models.DateTimeField(auto_now_add=True)

django/crumbs/forms.py
# imports, Django core
from django.forms import ModelForm
from django.forms import DateInput, FileInput, NumberInput, TextInput

# imports, this app
from crumbs.models import Expense


class ExpenseForm(ModelForm):

    class Meta:
        model = Expense
        fields = ['amount', 'date', 'purpose',]

        # CSS styling in Django forms
        # https://stackoverflow.com/questions/5827590/css-styling-in-django-forms
        widgets = {
            'amount': NumberInput(attrs={'class': 'form-control'}),
            'date': DateInput(attrs={'class': 'form-control'}),
            'purpose': TextInput(attrs={'class': 'form-control'}),
        }


# https://simpleisbetterthancomplex.com/tutorial/2016/08/01/how-to-upload-files-with-django.html
from crumbs.models import Receipt
class ReceiptForm(ModelForm):
    class Meta:
        model = Receipt
        fields = ['receipt',]
        widgets = {
            'receipt': FileInput(attrs={'class': 'custom-file-input'}),
        }
        # https://stackoverflow.com/questions/36905060/how-can-i-change-the-modelform-label-and-give-it-a-custom-name
        labels = {
            'receipt': 'Please select file to upload',
        }

django/crumbs/views.py
# imports, standard library

# imports, Django core
from django.shortcuts import render
from django.shortcuts import redirect

# imports, this app
from crumbs.libs.utils import my_time
from crumbs.libs.utils import mlreader
from .forms import ExpenseForm


def expense_create(request):
    if request.method == 'POST':
        form = ExpenseForm(request.POST)
        if form.is_valid():
            expense = form.save(commit=False)
            # do other things...
            try:
                expense.save()
            except:
                print("there was an error saving the form")
                pass

            return redirect('crumbs:about')
    else:
        #import requests
        #import json
        #from datetime import datetime
        #tentative = mlreader()
        #tentative_dict = json.loads(tentative.text)
        #tentative_amount = tentative_dict['extract']['AMOUNT']
        #tentative_purpose = tentative_dict['extract']['NAME']
        #tentative_date = datetime.strptime(tentative_dict['extract']['INVOICEDATE'], '%a, %d %b %Y %H:%M:%S %Z')
        #data = {
        #    'amount': tentative_amount,
        #    'purpose': tentative_purpose,
        #    'date': tentative_date,
        #}

        from datetime import datetime
        data = {
            'amount': '33',
            'date': datetime.today(),
            'purpose': 'pilfering!',
        }
        form = ExpenseForm(initial=data)

    context = {
        'title': 'Expense, create',
        'content_header': 'Expense, create',
        'form': form,
    }
    return render(request, 'crumbs/expense_create.html', context)


from django.shortcuts import get_object_or_404
from .models import Receipt
def expense_sand(request, receipt_id):
    if request.method == 'POST':
        form = ExpenseForm(request.POST)
        if form.is_valid():
            expense = form.save(commit=False)
            # do other things...
            try:
                expense.save()
            except:
                print("there was an error saving the form")
                pass
            return redirect('crumbs:about')
    else:
        #receipt = get_object_or_404(Receipt, pk=4)
        context = {
            'title': 'Expense, create',
            'content_header': 'Expense, create',
        }

        if receipt_id == 0:
            print('got a macht on the receipt_id!')
            data = {
                'amount': '',
                'date': '',
                'purpose': ''
            }
            pass
        else:
            receipt = get_object_or_404(Receipt, pk=receipt_id)
            context['receipt'] = receipt
            # here invoke function to process the receipt -> mlreader()
            from datetime import datetime
            data = {
                'amount': '33',
                'date': datetime.today(),
                'purpose': 'pilfering!',
            }

        form = ExpenseForm(initial=data)
        context['form'] = form

    #context = {
    #    'title': 'Expense, create',
    #    'content_header': 'Expense, create',
    #    'form': form,
    #    'receipt': receipt,
    #}
    return render(request, 'crumbs/expense_sand.html', context)

def expense_paper(request):
    return redirect('crumbs:expense_sand', receipt_id='0')


from .models import Expense
def expense_list(request):
    expenses = Expense.objects.all()
    context = {
        'title': 'Expenses, list',
        'page_header': 'Expenses, all of them',
        'expenses': expenses,
    }
    return render(request, 'crumbs/expense_list.html', context)


def about(request):
    context = {
        'title': 'About this app',
        'page_header': 'About this app',
        'bodymessage': "About this app",
    }
    #t = my_time()
    #print(type(t))
    #print(t)
    return render(request, 'crumbs/about.html', context)


from .forms import ReceiptForm
def receipt_upload(request):
    if request.method == 'POST':
        form = ReceiptForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('crumbs:about')
    else:
        form = ReceiptForm()
        context = {
            'title': 'Upload receipt',
            'page_header': 'Upload receipt',
            'form': form,
        }
    return render(request, 'crumbs/receipt_upload.html', context)


from .models import Receipt
def receipt_list(request):
    receipts = Receipt.objects.all()
    context = {
        'title': 'Receipts, list',
        'page_header': 'Receipts, all of them',
        'receipts': receipts,
    }
    return render(request, 'crumbs/receipt_list.html', context)


from django.shortcuts import get_object_or_404
def receipt_read(request, receipt_id):
    receipt = get_object_or_404(Receipt, pk=receipt_id)
    context = {
        'title': 'Receipt, read',
        'page_header': 'Receipt, read',
        'receipt': receipt,
    }
    return render(request, 'crumbs/receipt_read.html', context)

django/crumbs/templates/crumbs/about.html
{% extends 'base.html' %}

{% block content %}


<p>
  This app does record expenses and claims.
</p>


{% endblock content %}

django/crumbs/templates/crumbs/expense_create.html
{% extends 'base.html' %}


{% block content %}
    <h3>{{ content_header }}</h3>

    {% comment %}
    {% if user.is_authenticated %}
        {{ request.user.username }}
    {% endif %}
    {% endcomment %}


    <form action="{% url 'crumbs:expense_create' %}" method="POST">
        {% csrf_token %}

        {% for field in form %}
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">{{ field.label_tag }}</label>
                <div class="col-sm-10">
                    {{ field }}
                </div>
            </div>
        {% endfor %}

        <button type="submit" class="btn btn-primary">Save</button>
    </form>

{% endblock content %}

django/crumbs/templates/crumbs/expense_list.html
{% extends 'base.html' %}

{% block content %}


<div class="container">

    <h3 class="mb-4">{{ page_header }}</h3>


    {% for expense in expenses %}
        <p>{{ expense.purpose }}</p>

    {% comment %}
    <a href="{% url 'crumbs:receipt_read' receipt.id %}">See full picture</a>
    {% endcomment %}
    {% endfor %}


</div>


{% endblock content %}

django/crumbs/templates/crumbs/expense_sand.html
{% extends 'base.html' %}


{% block content %}
    <h3>{{ content_header }}</h3>

    {% comment %}
    {% if user.is_authenticated %}
        {{ request.user.username }}
    {% endif %}
    {% endcomment %}


    <form action="{% url 'crumbs:expense_create' %}" method="POST">
        {% csrf_token %}

        {% for field in form %}
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">{{ field.label_tag }}</label>
                <div class="col-sm-10">
                    {{ field }}
                </div>
            </div>
        {% endfor %}

        <button type="submit" class="btn btn-primary">Save</button>
    </form>

    <div class="embed-responsive embed-responsive-1by1 mb-4">
    <embed class="embed-responsive-item" src="{% if receipt.receipt %}{{ receipt.receipt.url }}{% endif %}">
    </div>

{% endblock content %}

django/crumbs/templates/crumbs/receipt_list.html
{% extends 'base.html' %}

{% block content %}


<div class="container">

    <h3 class="mb-4">{{ page_header }}</h3>

    <p class="mb-4">Using the <code>embed</code> tag</p>
    {% for receipt in receipts %}
    <div class="embed-responsive embed-responsive-21by9 mb-4">
        <embed class="embed-responsive-item" src="{% if receipt.receipt %}{{ receipt.receipt.url }}{% endif %}">
    </div>

    <a href="{% url 'crumbs:receipt_read' receipt.id %}">See full picture</a>
    {% endfor %}:wq

</div>


{% endblock content %}

django/crumbs/templates/crumbs/receipt_read.html
{% extends 'base.html' %}

{% block content %}


<div class="container">

    <h3 class="mb-4">{{ page_header }}</h3>

    <p class="mb-4">Using the <code>embed</code> tag</p>
    {% comment %}
    {% for receipt in receipts %}
    {% endcomment %}
    <div class="embed-responsive embed-responsive-1by1 mb-4">
        <embed class="embed-responsive-item" src="{% if receipt.receipt %}{{ receipt.receipt.url }}{% endif %}">
    </div>

    {% comment %}
    {% endfor %}
    {% endcomment %}

</div>


{% endblock content %}

django/crumbs/templates/crumbs/receipt_upload.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <h3 class="mb-4">{{ page_header }}</h3>

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        {% for field in form %}
        <div class="custom-file mb-4">
            {{ field }}
            <label class="custom-file-label">{{ field.label_tag }}</label>
        </div>
        {% endfor %}

        <button type="submit" class="btn btn-primary">Upload</button>
    </form>

</div>

{% endblock content %}